/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef SIGPONG_PRIVATE_H
#define SIGPONG_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"0.5.3.191"
#define VER_MAJOR	0
#define VER_MINOR	5
#define VER_RELEASE	3
#define VER_BUILD	191
#define COMPANY_NAME	""
#define FILE_VERSION	"0.5.3.191"
#define FILE_DESCRIPTION	"Pong"
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	"2022"
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	""
#define PRODUCT_NAME	"SIGIL Pong 32bit"
#define PRODUCT_VERSION	"0.5.3.191"

#endif /*SIGPONG_PRIVATE_H*/
